name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET 9 (preview)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publicar
        run: dotnet publish --configuration Release --output ./publish

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fazer deploy no Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'oarmario42'
          package: ./publish